services:
  db:
    image: postgres:16
    container_name: budgetize_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234$
      POSTGRES_DB: budgetize
    ports:
      - "8080:5432"
    volumes:
      - budgetize_db:/var/lib/postgresql/data

volumes:
  budgetize_db:
    driver: local
