services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: fer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - budgetize_db:/var/lib/mysql

volumes:
  budgetize_db:
    driver: local
